version: '3'
services:
  node:
    build: .
    command: npm run dev
    image: ellankz/node-app:latest
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
    restart: always
    volumes:
      - ./log:/usr/app/log/
      - ./src:/usr/app/src/
    networks:
      - appNetwork
  postgres:
    build: ./database
    image: ellankz/node-app-postgres:latest
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - appNetwork
networks:
  appNetwork:
volumes:
  pgdata:
